name = "mutabiq-ai"
compatibility_date = "2024-09-01"

[build]
command = "npx @cloudflare/next-on-pages@1 build"

# Point to the Worker entrypoint created by next-on-pages
main = "./.vercel/output/static/_worker.js"
